/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-StudyBuddy-W8F7UqYj6Vusfg6Nseq8QDyh2lr8LIRQ",
  "version": "2020-11-20"
}

export default ebconfig;