/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-StudyBuddy-M5xqoMxzjoQMaPYIY4pPm1joksgnIQaV",
  "version": "2020-11-20"
}

export default ebconfig;